/**
 * Code Generator
 * Converts an AnimationSpec into executable TypeScript React component code.
 *
 * The generated code is a self-contained React component that:
 * - Reads AnimationSpec as props
 * - Renders each step on an HTML5 Canvas using requestAnimationFrame
 * - Supports the core tool: drawTangentLine (and others as stubs)
 */

/* eslint-disable */
import { AnimationSpec, AnimationStep } from "./types";

export function generateAnimationCode(spec: AnimationSpec): string {
  const stepsCode = spec.steps
    .map((step, i) => generateStepCode(step, i))
    .join("\n\n");

  return `/**
 * AUTO-GENERATED by AnimAgent
 * Concept: ${spec.concept}
 * Type: ${spec.animationType}
 * Duration: ${spec.durationMs}ms
 */
import { AnimationSpec } from "@/lib/agent/types";

interface Point { x: number; y: number }

// ── Math helpers ────────────────────────────────────────────────────────────

function evalExpr(expr: string, x: number): number {
  // Safe evaluation using pre-defined math functions
  const safeScope: Record<string, unknown> = {
    x,
    sin: Math.sin,
    cos: Math.cos,
    tan: Math.tan,
    sqrt: Math.sqrt,
    abs: Math.abs,
    pi: Math.PI,
    e: Math.E,
    log: Math.log,
    pow: Math.pow,
  };
  // Replace ^ with ** for JS exponentiation
  const jsExpr = expr.replace(/\\^/g, "**");
  const fn = new Function(
    ...Object.keys(safeScope),
    \`"use strict"; return (\${jsExpr});\`
  );
  return fn(...Object.values(safeScope));
}

function derivative(expr: string, x: number, h = 1e-5): number {
  return (evalExpr(expr, x + h) - evalExpr(expr, x - h)) / (2 * h);
}

// ── Canvas coordinate transform ─────────────────────────────────────────────

function toCanvas(
  mx: number, my: number,
  xMin: number, xMax: number, yMin: number, yMax: number,
  w: number, h: number
): Point {
  return {
    x: ((mx - xMin) / (xMax - xMin)) * w,
    y: h - ((my - yMin) / (yMax - yMin)) * h,
  };
}

// ── Step renderers ──────────────────────────────────────────────────────────

${stepsCode}

// ── Main exported component ─────────────────────────────────────────────────

export interface AnimationPlayerProps {
  spec: AnimationSpec;
  width?: number;
  height?: number;
}

export default function AnimationPlayer({ spec, width = 640, height = 400 }: AnimationPlayerProps) {
  if (typeof window === "undefined") return null;

  const canvasRef = typeof document !== "undefined"
    ? { current: null as HTMLCanvasElement | null }
    : { current: null };

  return {
    spec,
    render: (ctx: CanvasRenderingContext2D, progress: number) => {
      ctx.clearRect(0, 0, width, height);
      drawGrid(ctx, width, height);
      const elapsed = progress * spec.durationMs;
      spec.steps.forEach((step, i) => {
        if (elapsed >= step.startMs) {
          const stepProgress = Math.min(
            1,
            (elapsed - step.startMs) / step.durationMs
          );
          renderStep(ctx, step, stepProgress, width, height);
        }
      });
    }
  };
}

function drawGrid(ctx: CanvasRenderingContext2D, w: number, h: number) {
  ctx.strokeStyle = "#E5E7EB";
  ctx.lineWidth = 1;
  for (let x = 0; x <= w; x += 40) {
    ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, h); ctx.stroke();
  }
  for (let y = 0; y <= h; y += 40) {
    ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(w, y); ctx.stroke();
  }
  // Axes
  ctx.strokeStyle = "#374151";
  ctx.lineWidth = 2;
  ctx.beginPath(); ctx.moveTo(w / 2, 0); ctx.lineTo(w / 2, h); ctx.stroke();
  ctx.beginPath(); ctx.moveTo(0, h / 2); ctx.lineTo(w, h / 2); ctx.stroke();
}

function renderStep(
  ctx: CanvasRenderingContext2D,
  step: AnimationStep,
  progress: number,
  w: number,
  h: number
) {
  switch (step.toolName) {
    case "drawFunctionGraph":
      renderDrawFunctionGraph(ctx, step.params, progress, w, h);
      break;
    case "drawTangentLine":
      renderDrawTangentLine(ctx, step.params, progress, w, h);
      break;
    case "highlightIntegralArea":
      renderHighlightIntegralArea(ctx, step.params, progress, w, h);
      break;
    case "addMathLabel":
      renderAddMathLabel(ctx, step.params, progress, w, h);
      break;
    case "showStepByStep":
      renderShowStepByStep(ctx, step.params, progress, w, h);
      break;
  }
}
`;
}

function generateStepCode(step: AnimationStep, _index: number): string {
  switch (step.toolName) {
    case "drawFunctionGraph":
      return generateDrawFunctionGraph(step);
    case "drawTangentLine":
      return generateDrawTangentLine(step);
    case "highlightIntegralArea":
      return generateHighlightIntegralArea(step);
    case "addMathLabel":
      return generateAddMathLabel(step);
    case "showStepByStep":
      return generateShowStepByStep(step);
    default:
      return `// Unknown tool: ${step.toolName}`;
  }
}

function generateDrawFunctionGraph(_step: AnimationStep): string {
  return `
function renderDrawFunctionGraph(
  ctx: CanvasRenderingContext2D,
  params: Record<string, unknown>,
  progress: number,
  w: number, h: number
) {
  const expr = String(params.expression ?? "x");
  const xMin = Number(params.xMin ?? -5);
  const xMax = Number(params.xMax ?? 5);
  const yMin = Number(params.yMin ?? -5);
  const yMax = Number(params.yMax ?? 5);
  const color = String(params.color ?? "#3B82F6");
  const animateDraw = Boolean(params.animateDraw ?? true);

  const drawUpTo = animateDraw ? xMin + (xMax - xMin) * progress : xMax;
  const steps = 400;
  const dx = (xMax - xMin) / steps;

  ctx.strokeStyle = color;
  ctx.lineWidth = 2.5;
  ctx.beginPath();
  let first = true;
  for (let xi = xMin; xi <= drawUpTo; xi += dx) {
    const yi = evalExpr(expr, xi);
    if (!isFinite(yi)) { first = true; continue; }
    const p = toCanvas(xi, yi, xMin, xMax, yMin, yMax, w, h);
    if (first) { ctx.moveTo(p.x, p.y); first = false; }
    else ctx.lineTo(p.x, p.y);
  }
  ctx.stroke();

  if (params.label && progress > 0.9) {
    ctx.fillStyle = color;
    ctx.font = "bold 14px monospace";
    const labelX = xMax * 0.7;
    const labelY = evalExpr(expr, labelX);
    const lp = toCanvas(labelX, labelY, xMin, xMax, yMin, yMax, w, h);
    ctx.fillText(String(params.label), lp.x + 8, lp.y - 8);
  }
}`;
}

function generateDrawTangentLine(_step: AnimationStep): string {
  return `
function renderDrawTangentLine(
  ctx: CanvasRenderingContext2D,
  params: Record<string, unknown>,
  progress: number,
  w: number, h: number
) {
  const expr = String(params.expression ?? "x^2");
  const xMin = Number(params.xMin ?? -4);
  const xMax = Number(params.xMax ?? 4);
  const yMin = -2;
  const yMax = 12;
  const curveColor = String(params.curveColor ?? "#3B82F6");
  const tangentColor = String(params.tangentColor ?? "#F59E0B");

  // Always draw the base curve first
  ctx.strokeStyle = curveColor;
  ctx.lineWidth = 2.5;
  ctx.beginPath();
  const steps = 300;
  const dx = (xMax - xMin) / steps;
  let first = true;
  for (let xi = xMin; xi <= xMax; xi += dx) {
    const yi = evalExpr(expr, xi);
    if (!isFinite(yi)) { first = true; continue; }
    const p = toCanvas(xi, yi, xMin, xMax, yMin, yMax, w, h);
    if (first) { ctx.moveTo(p.x, p.y); first = false; }
    else ctx.lineTo(p.x, p.y);
  }
  ctx.stroke();

  // Sliding tangent point
  const animateSlide = Boolean(params.animateSlide ?? true);
  const atX = Number(params.atX ?? 0);
  const currentX = animateSlide
    ? xMin + (xMax - xMin) * progress
    : atX;

  const currentY = evalExpr(expr, currentX);
  const slope = derivative(expr, currentX);

  // Draw tangent line (y - y0 = m(x - x0))
  const tLen = (xMax - xMin) * 0.35;
  const tx1 = currentX - tLen;
  const ty1 = currentY - slope * tLen;
  const tx2 = currentX + tLen;
  const ty2 = currentY + slope * tLen;

  ctx.strokeStyle = tangentColor;
  ctx.lineWidth = 2;
  ctx.setLineDash([6, 4]);
  ctx.beginPath();
  const p1 = toCanvas(tx1, ty1, xMin, xMax, yMin, yMax, w, h);
  const p2 = toCanvas(tx2, ty2, xMin, xMax, yMin, yMax, w, h);
  ctx.moveTo(p1.x, p1.y);
  ctx.lineTo(p2.x, p2.y);
  ctx.stroke();
  ctx.setLineDash([]);

  // Tangent point dot
  const pp = toCanvas(currentX, currentY, xMin, xMax, yMin, yMax, w, h);
  ctx.fillStyle = tangentColor;
  ctx.beginPath();
  ctx.arc(pp.x, pp.y, 5, 0, 2 * Math.PI);
  ctx.fill();

  // Slope label
  if (params.showSlopeLabel) {
    ctx.fillStyle = "#1F2937";
    ctx.font = "bold 15px monospace";
    const slopeText = \`slope = \${slope.toFixed(2)}\`;
    ctx.fillText(slopeText, pp.x + 12, pp.y - 12);

    // x label
    ctx.fillStyle = "#6B7280";
    ctx.font = "13px monospace";
    ctx.fillText(\`x = \${currentX.toFixed(2)}\`, pp.x + 12, pp.y + 8);
  }
}`;
}

function generateHighlightIntegralArea(_step: AnimationStep): string {
  return `
function renderHighlightIntegralArea(
  ctx: CanvasRenderingContext2D,
  params: Record<string, unknown>,
  progress: number,
  w: number, h: number
) {
  const expr = String(params.expression ?? "sin(x)");
  const fromX = Number(params.fromX ?? 0);
  const toX = Number(params.toX ?? Math.PI);
  const xMin = fromX - 1;
  const xMax = toX + 1;
  const yMin = -1.5;
  const yMax = 1.5;
  const fillColor = String(params.fillColor ?? "rgba(59,130,246,0.3)");

  const fillUpTo = fromX + (toX - fromX) * progress;

  ctx.fillStyle = fillColor;
  ctx.beginPath();
  const origin = toCanvas(fromX, 0, xMin, xMax, yMin, yMax, w, h);
  ctx.moveTo(origin.x, origin.y);
  const steps = 200;
  const dx = (fillUpTo - fromX) / steps;
  for (let xi = fromX; xi <= fillUpTo; xi += dx) {
    const yi = evalExpr(expr, xi);
    const p = toCanvas(xi, yi, xMin, xMax, yMin, yMax, w, h);
    ctx.lineTo(p.x, p.y);
  }
  const endP = toCanvas(fillUpTo, 0, xMin, xMax, yMin, yMax, w, h);
  ctx.lineTo(endP.x, endP.y);
  ctx.closePath();
  ctx.fill();
}`;
}

function generateAddMathLabel(_step: AnimationStep): string {
  return `
function renderAddMathLabel(
  ctx: CanvasRenderingContext2D,
  params: Record<string, unknown>,
  progress: number,
  w: number, h: number
) {
  const fadeIn = Boolean(params.fadeIn ?? true);
  const alpha = fadeIn ? Math.min(1, progress * 2) : 1;
  ctx.globalAlpha = alpha;
  ctx.fillStyle = String(params.color ?? "#1F2937");
  ctx.font = \`bold \${Number(params.fontSize ?? 16)}px serif\`;
  const px = (Number(params.x ?? 0) + 5) / 10 * w;
  const py = h / 2 - (Number(params.y ?? 0)) / 2 * (h / 2);
  ctx.fillText(String(params.text ?? ""), px, py);
  ctx.globalAlpha = 1;
}`;
}

function generateShowStepByStep(_step: AnimationStep): string {
  return `
function renderShowStepByStep(
  ctx: CanvasRenderingContext2D,
  params: Record<string, unknown>,
  progress: number,
  w: number, h: number
) {
  const steps = (params.steps as string[]) ?? [];
  const visibleCount = Math.floor(progress * steps.length) + 1;
  const xOffset = w * 0.62;
  ctx.fillStyle = "rgba(255,255,255,0.92)";
  ctx.fillRect(xOffset - 8, 20, w - xOffset, steps.length * 32 + 16);
  steps.slice(0, visibleCount).forEach((s: string, i: number) => {
    ctx.fillStyle = i === visibleCount - 1 ? "#2563EB" : "#374151";
    ctx.font = i === visibleCount - 1 ? "bold 15px monospace" : "14px monospace";
    ctx.fillText(s, xOffset, 48 + i * 32);
  });
}`;
}
